spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:8080/db_example
    username: akal
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update